### ISSUE TITLE
Allow easy export of complex fields

### ISSUE THREAD

**Issue by KeyboardCowboy** [Lullabot/github-export#3]
Some fields are not simple key:value pairs, but are more complex objects (labels, for example).  We don't want the entire object of the field, but a text value from the object, such as its text value or its background color.  We need to define a way to extract subfields from those objects.

### Potential Solution:
```yaml
MySearch:
  AllIssues:
    fields: title,labels:name,html_url
```

![Cursor_and_github_–_GithubExporter_js](https://github.com/Lullabot/github-export/assets/1002715/4318108a-c836-4999-932c-590790ec2805)
